
- name: ---- create directory in /home/reza ----
  file:
    path: /home/reza/testdir1
    state: directory
    owner: reza
    group: reza
    mode: 0755
  tags: [create_dir]

- name: ---- create file in /home/reza/testdir
  file:
    path: /home/reza/testdir1/file1
    state: touch
    owner: reza
    group: reza
    mode: 0755
  tags: [create_file]


- name: ---- show my user list ----
  debug:
    msg: "{{user_list[0]}}"
  tags: [show_user_list]


- name: ---- show my user list 2----
  debug:
    msg: "{{user_list2}}"
  tags: [show_user_list2]


- name: --- create var and test in tasks main yaml ----
  set_fact:
    myvar: "salam"
- name: ----show my var ----
  debug:
    msg: "{{myvar}}"
  tags: [show_my_var]

- name: ----show my os family ----
  debug:
    msg: "{{ansible_os_family}}"
  tags: [show_my_os_family]

- name: ----show my http port as group vars----
  debug:
    msg: "{{http_port}}"
  tags: [show_my_http_port]

- name: ---- command module ----
  command: cat file1
  args:
    chdir: /home/reza/testdir1
  register: catty
  tags: [show_command_module]

- name: ---- show result of command module ---
  debug:
    msg: "{{catty.stdout}}"
  tags: [show_command_module]


- name: ---- command module Execise for df -h ----
  command: df -h
  register: df
  tags: [show_command_module_ex8_df]

- name: ---- show result of command module for df -h Exercise---
  debug:
    msg: "{{df.stdout}}"
  tags: [show_command_module_ex8_df]

- name: ---- show my user name ----
  debug:
    msg: "{{user.name}}"
  tags: [show_var_username]

- name: ---- show my user email ----
  debug:
    msg: "{{user.email}}"
  tags: [show_var_email]






- name: --- copy module ---
  copy:
    src: file1
    dest: /home/reza/testdir1
    owner: reza
    group: reza
    mode: 0644
    backup: yes
    force: yes
  tags: [copy_module]



- name: --- copy module in remote machines ---
  copy:
    src: /home/reza/testdir1/file1
    dest: /home/reza
    owner: reza
    group: reza
    mode: 0644
    backup: yes
    remote_src: yes
    # force: yes
  tags: [copy_module_remote]



- name: --- fetch module ---
  fetch:
    src: /home/reza/testdir1/file1
    dest: /home/reza
  tags: [fetch_module]


- name: --- fetch module flat ---
  fetch:
    src: /home/reza/testdir1/file1
    dest: /home/reza/
    flat: yes
  tags: [fetch_module_flat]

- name: --- fetch module checksum ---
  fetch:
    src: /home/reza/testdir1/file1
    dest: /home/reza/
    flat: yes
    validate_checksum: no
  tags: [fetch_module_checksum]



- name: --- group module ---
  group:
    name: mamad
    state: present
  tags: [group_module]

- name: --- group module ---
  group:
    name: devops
    state: present
  tags: [group_module]

- name: --- user module ---
  user:
    name: user1
    group: devops
    state: present #absent for delete
    shell: /bin/bash
    home: /tmp/reza
    password: 123
  tags: [user_module]


- name: --- lineinfile module -- 
  lineinfile:
    path: ~/.bashrc # if it doesn't exist it will append at the end of the file
    insertafter: 'alias sss=echo {{myvarinbash}} '
    line: 'alias ssss=echo {{myvarinbash}}'
  tags: [lineinfile_module]


- name: --- replace module -- 
  replace:
    path: ~/.bashrc # if it doesn't exist it will append at the end of the file
    regexp: 'alias ssss=echo {{myvarinbash}} '
    replace: 'alias ffff=echo {{myvarinbash}}'
    # after: 'start after line'
    # before: 'start before line'
    # backup: yes
  tags: [replace_module]


- name: Ensure /etc/yum.repos.d exists
  file:
    path: /etc/yum.repos.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [ensure_yum_repo_dir]


- name: --- yum repos module ---
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux
    baseurl: http://download.fedoraproject.org/pub/epel/9/Everything/x86_64/
    gpgcheck: no
    enabled: yes
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [yum_repo_module]

- name: --- yum module ---
  yum:
    name: nginx
    state: latest
    exclude: kernel*
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [yum_module]

- name: --- yum list ---
  yum:
    list: ansible
  register: yum_out
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [yum_list_module]

- name: --- yum list print out ---
  debug:
    msg: "Installed package details: {{ yum_out.results }}"
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [yum_list_module]

- name: --- apt module ---
  apt:
    name: nginx # '*' updates all packages if combined with `state: latest`
    state: latest # 'present' installs; 'latest' installs or updates
  when: ansible_facts['os_family'] == 'Debian'
  tags: [apt_module]

# - name: --- apt dpkg module ---
#   apt:
#     deb: /opt/deb.pkg
#   when: ansible_facts['os_family'] == 'Debian'
#   tags: [apt_module_dpkg]




- name: ---- Copy NGINX config for Ubuntu ----
  template:
    src: templates/ubuntu-nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  when: ansible_facts['os_family'] == "Debian"
  tags: [template_module]

- name: ---- Copy NGINX config for Rocky or CentOS ----
  template:
    src: templates/rocky-nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  when: ansible_facts['os_family'] == "RedHat"
  tags: [template_module]


- name: ---- Change NGINX config for Ubuntu ----
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: '        listen       8081;'
    line: '        listen       8082;'
  when: ansible_facts['os_family'] == "Debian"
  tags: [lineinfile_module]

- name: ---- Chnage NGINX config for Rocky or CentOS ----
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: '        listen       8081;'
    line: '        listen       8082;'
  when: ansible_facts['os_family'] == "RedHat"
  tags: [lineinfile_module]


- name: ---- Change NGINX config for Ubuntu ----
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: '        listen       8081;'
    line: '        listen       8080;'
  when: ansible_facts['os_family'] == "Debian"
  tags: [lineinfile_module]

- name: ---- Chnage NGINX config for Rocky or CentOS ----
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: '        listen       8081;'
    line: '        listen       8080;'
  when: ansible_facts['os_family'] == "RedHat"
  tags: [lineinfile_module]



- name: ---- Replace module with regex ----
  replace:
    path: /etc/nginx/nginxconf
    regexp: '        listen       8081;'
    replace: '        listen       80;'
    # after: 'start after line. *'
    # before: 'start before line.*'
    # backup: yes
  tags: [replace_module]


# - name: --- Service Module enabled  ----
#   service:
#     name: nginx
#     enabled: yes
#   tags: [service_module]

- name: --- Service Module started  ----
  service:
    name: nginx
    state: started
  tags: [service_module]

# - name: --- Service Module restarted  ----
#   service:
#     name: nginx
#     state: restarted
#   tags: [service_module]

# - name: --- Service Module started  ----
#   service:
#     name: nginx
#     state: stopped
#   tags: [service_module]


- name: --- Archieve Module   ----
  archive:
    path: /home/reza/testdir1/*
    dest: /home/reza/test.tar.gz
    exclude_path:
      - /home/reza/testdir1/file2
      - /home/reza/testdir1/file1.*
  tags: [archive_module]



- name: --- Unarchieve Module   ----
  unarchive:
    src: /home/reza/test.tar.gz
    dest: /home/reza/testdir2
    # exclude_path:
      # - f3
    keep_newer: no
    remote_src: yes
    # creates: no
  tags: [unarchive_module]


- name: ---- wait module ---
  wait_for: 
    timeout: 10
  delegate_to: localhost
  tags: [wait_module]

- name: ---- check service status ion log with wait ----
  wait_for:
    path: /var/log/nginx/access.log
    search_regex: "start worker processes"
  tags: [wait_regex_module]

- name: ---- wait for port ----
  wait_for:
    # host: 192.168.68.3 # optional
    port: 80
    delay: 10
    state: started
  tags: [wait_for_80]


# - name: ---- ignore error ----
#   command: /bin/false
#   ignore_error: yes
#   tags: [ignore_error_module]

# - name: ---- after error ----
#   debug:
#     msg: "After Error"
#   tags: [ignore_error_module]


# - name: ---- update all package ----
#   yum:
#     name: *
#     state: latest
#   async: 7500
#   poll: 5 # every 5 second check the task and 0 for dont check that
#   tags: [async_module]


- name: --- wait for connection ----
  wait_for_connection:
    timeout: 10
    delay: 10
    sleep: 5
  tags: [wait_for_connection_module]

- name: reboot machine
  shell: 'reboot'
  tags: [reboot_machines]



- name: --- wait for connection after reboot  ----
  wait_for_connection:
    timeout: 300
    delay: 5
    sleep: 5
  tags: [reboot_machines]

- name: ---- after Reboot ----
  debug:
    msg: "After Reboot"
  tags: [reboot_machines]



- name: ----  Reboot module----
  reboot:
    reboot_timeout: 300
  tags: [reboot_module]


- name: git module
  git:
    repo: https://github.com/mohammadrezachegini/NodeJS-Projects
    dest: /opt/
    # revision: v1.0
  tags: [git_mode]


- name: set timezone to vancouver
  timezone:
    name: America/Vancouver
  tags: [timezone_module]